import type { FitnessModule, FitnessModuleCategory } from '../types';
import { categoryIonIcon, type IoniconName } from './icons';

const CATEGORY_DEFAULTS: Record<FitnessModuleCategory, IoniconName> = {
  mindBody: 'flower-outline',
  anatomy: 'body-outline',
  brainGames: 'game-controller-outline',
  calculators: 'calculator-outline',
  trackers: 'pulse-outline',
  workouts: 'barbell-outline',
  education: 'book-outline',
};

/** Module-specific overrides — everything else falls back to category / wellness category. */
const MODULE_OVERRIDES: Record<string, IoniconName> = {
  breathing: 'water-outline',
  meditation: 'timer-outline',
  'mindfulness-toolkit': 'construct-outline',
  mindfulness: 'flower-outline',
  stretching: 'body-outline',
  yoga: 'body-outline',
  'sleep-tools': 'bed-outline',
  'bedtime-wind-down': 'moon-outline',
  'power-nap': 'bed-outline',
  'circadian-reset': 'sunny-outline',
  'sleep-quality-log': 'bed-outline',
  'body-scan': 'body-outline',
  'loving-kindness': 'heart-outline',
  'walking-meditation': 'walk-outline',
  'breath-anchor': 'leaf-outline',
  'progressive-relax': 'water-outline',
  'five-minute-calm': 'timer-outline',
  'tension-release': 'body-outline',
  'evening-unwind': 'moon',
  'heart-hologram': 'pulse',
  'heart-lungs-hologram': 'heart-circle-outline',
  'heart-conduction-system': 'git-network-outline',
  'brain-model': 'bulb-outline',
  'lung-model': 'fitness-outline',
  'eye-model': 'eye-outline',
  'kidney-model': 'water-outline',
  'liver-model': 'nutrition-outline',
  'stomach-model': 'nutrition-outline',
  'spine-model': 'body-outline',
  'skeleton-model': 'skull-outline',
  'muscle-model': 'barbell-outline',
  'anatomy-study': 'body-outline',
  'nervous-system': 'flash-outline',
  'memory-match': 'grid-outline',
  'reaction-time': 'flash-outline',
  'pattern-recognition': 'shapes-outline',
  'quick-math': 'calculator-outline',
  'word-recall': 'chatbubble-outline',
  'number-sequence': 'list-outline',
  'color-match': 'color-palette-outline',
  'attention-switch': 'swap-horizontal-outline',
  'speed-reading': 'book-outline',
  'focus-training': 'locate-outline',
  'visual-puzzle': 'extension-puzzle-outline',
  'mental-rotation': 'sync-outline',
  bmi: 'scale-outline',
  bmr: 'flame-outline',
  macros: 'nutrition-outline',
  'heart-rate-zones': 'heart-outline',
  'vo2-max': 'fitness-outline',
  hydration: 'water-outline',
  'sleep-debt': 'bed-outline',
  'one-rep-max': 'barbell-outline',
  'intermittent-fast': 'timer-outline',
  'body-fat': 'body-outline',
  'protein-calculator': 'nutrition-outline',
  'waist-hip': 'resize-outline',
  steps: 'footsteps-outline',
  'heart-rate-tracker': 'heart-outline',
  'blood-pressure': 'pulse-outline',
  'blood-glucose': 'water-outline',
  'hydration-tracker': 'water-outline',
  'pain-scale': 'bandage-outline',
  'energy-level': 'flash-outline',
  'mindfulness-tracker': 'flower-outline',
  'workout-library': 'barbell-outline',
  'sports-injury': 'medkit-outline',
  'senior-fitness': 'walk-outline',
  'walking-running': 'footsteps-outline',
  anxiety: 'happy-outline',
  depression: 'heart-outline',
  'stress-disorders': 'flame-outline',
  insomnia: 'moon-outline',
  'back-pain': 'body-outline',
  'neck-pain': 'body-outline',
  'posture-analyzer': 'body-outline',
  'stress-assessment': 'analytics-outline',
  'chronic-stress': 'flash-outline',
  'high-bp': 'heart-outline',
  diabetes: 'water-outline',
  'smoking-cessation': 'leaf-outline',
  menopause: 'flower-outline',
  'long-covid': 'medical-outline',
  'meal-planner': 'restaurant-outline',
  'high-protein-meals': 'nutrition-outline',
  'food-scan': 'camera-outline',
  'body-metrics': 'pulse-outline',
  'activity-dashboard': 'analytics-outline',
  'brain-games-hub': 'game-controller-outline',
};

export function fitnessModuleIonIcon(module: Pick<FitnessModule, 'id' | 'category' | 'wellnessCategory'>): IoniconName {
  if (MODULE_OVERRIDES[module.id]) return MODULE_OVERRIDES[module.id];
  if (module.wellnessCategory) return categoryIonIcon(module.wellnessCategory);
  return CATEGORY_DEFAULTS[module.category] ?? 'apps-outline';
}
